package com.linjc.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePersoninfo<M extends BasePersoninfo<M>> extends Model<M> implements IBean {

	public M setNumId(java.lang.Integer numId) {
		set("numId", numId);
		return (M)this;
	}
	
	public java.lang.Integer getNumId() {
		return getInt("numId");
	}

	public M setSiteName(java.lang.String siteName) {
		set("siteName", siteName);
		return (M)this;
	}
	
	public java.lang.String getSiteName() {
		return getStr("siteName");
	}

	public M setSiteAddress(java.lang.String siteAddress) {
		set("siteAddress", siteAddress);
		return (M)this;
	}
	
	public java.lang.String getSiteAddress() {
		return getStr("siteAddress");
	}

	public M setAccountNumber(java.lang.String accountNumber) {
		set("accountNumber", accountNumber);
		return (M)this;
	}
	
	public java.lang.String getAccountNumber() {
		return getStr("accountNumber");
	}

	public M setPassWord(java.lang.String passWord) {
		set("passWord", passWord);
		return (M)this;
	}
	
	public java.lang.String getPassWord() {
		return getStr("passWord");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
