package com.linjc.model;

import com.linjc.model.BasePersoninfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Personinfo extends BasePersoninfo<Personinfo> {
	public static final Personinfo dao = new Personinfo().dao();
}
